### ISSUE TITLE
Cannot recognize the end of an Actually Ed the Undying run

### ISSUE THREAD

**Issue by bestwithrice** [docrostov/ScotchLog#2]
![image](https://user-images.githubusercontent.com/61367204/95122358-5fa51600-071e-11eb-8552-19d051e6b39a.png)

After concluding an Ed run and choosing one of the standard six classes, running the parser results in the following error (see above image for the Mafia output): 

> ERROR: This didn't include the end of a run. Try again?

**Comment by docrostov** [comment]
wow i solved this a long time ago and never closed the issue lol

this works now, in theory. if not, let me know! sorry for, uh, being... 2.5 years late in replying lmao what
