### ISSUE TITLE
repeated reports of a bug that is not a bug

### ISSUE THREAD

**Issue by docrostov** [docrostov/ScotchLog#6]
this is kind of a funny issue. at least 5 times now i have gotten personal reports that scotchlog is "hung" because scotchlog just prints out the usual 3 line thing. in actuality, scotchlog has successfully done the requested operation and dropped the files in the user's data folder. but people don't realize that because i don't print to CLI "access your log in [file location]". i should just... add that lol

**Comment by txster** [comment]
Well, I was coming to say exactly this here instead of pinging you on Discord, so this gets a +1 from me ;-)

_NOW_ I know to look for the file in Mafia's data folder, but even just a "Done!" would be great, even without details to the file.

**Comment by docrostov** [comment]
i have finally, FINALLY fixed this
